# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: forbid-submodules
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace
        exclude: 'renv/.*'
      - id: end-of-file-fixer
        exclude: '\.Rd'

  - repo: https://github.com/crate-ci/typos
    rev: v1.28.3
    hooks:
      - id: typos
        exclude: '\.nb\.html'

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9003
    hooks:

      - id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
      # codemeta must be above use-tidy-description when both are used
      # -   id: codemeta-description-updated
      - id: use-tidy-description
      - id: lintr
      - id: parsable-R
      - id: no-browser-statement
      - id: no-debug-statement
      - id: deps-in-desc
        exclude: 'docker/.*|renv/.*|data-raw/.*'

ci:
  autofix_prs: true
  autoupdate_schedule: quarterly
